apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-flask-app
  template:
    metadata:
      labels:
        app: my-flask-app
    spec:
      containers:
      - name: my-flask-container
        image: 730335323907.dkr.ecr.ap-south-1.amazonaws.com/my_monitoring_app_image:latest

        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: ecr-secret
